### ISSUE TITLE
SERV cannot run in fusesoc

### ISSUE THREAD

**Issue by YiminGao0113** [olofk/serv#115]
Hi, could you help me with this issue? When I tried to run fusesoc run --target=lint serv
this error shows up: 
INFO: Preparing ::serv:1.2.1
Traceback (most recent call last):
  File "/home/yg9bq/.local/bin/fusesoc", line 8, in <module>
    sys.exit(main())
  File "/home/yg9bq/.local/lib/python3.6/site-packages/fusesoc/main.py", line 672, in main
    fusesoc(args)
  File "/home/yg9bq/.local/lib/python3.6/site-packages/fusesoc/main.py", line 662, in fusesoc
    args.func(fs, args)
  File "/home/yg9bq/.local/lib/python3.6/site-packages/fusesoc/main.py", line 316, in run
    edam_file, backend = fs.get_backend(core, flags, args.backendargs)
  File "/home/yg9bq/.local/lib/python3.6/site-packages/fusesoc/fusesoc.py", line 171, in get_backend
    edam=edam, work_root=work_root, verbose=self.config.verbose
  File "/home/yg9bq/.local/lib/python3.6/site-packages/edalize/edatool.py", line 183, in __init__
    loader=PackageLoader(__package__, "templates"),
  File "/home/yg9bq/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 291, in __init__
    assert loader is not None, "A loader was not found for the package."
AssertionError: A loader was not found for the package.

Thanks in advance!!

**Comment by anudeepdharavathu** [comment]
how did you resolve this issue?
can you please help? I have the same issue.
